; PlatformIO Project Configuration File
[env:esp32-s3-devkitc-1]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.partitions = default_8MB.csv
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=y
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0

